game_sale/game_sale/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls import handler404
from django.contrib import admin
from django.views.generic import RedirectView
from sales.views import MainView, SaleView

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'game_sale.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^docs/', include('backend.urls')),
    url(r'^sales/', include('sales.urls')),

    url(r'^$', MainView.as_view(), name='main'),
    url(r'^sale/(?P<pk>\d+)/$', SaleView.as_view(), name='sale-detail'),

    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT})
)

handler404 = RedirectView.as_view(permanent=False, url='/')

game_sale/sales/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from sales.views import ParseView, StoresView, SalesView, BestView, SearchView, SaleView, SleepView


urlpatterns = patterns('',
    url(r'^sleep/$', SleepView.as_view()),
    url(r'^parse/$', ParseView.as_view()),
    url(r'^parse/(?P<store_name>\w+)/$', ParseView.as_view()),
    url(r'^stores/$', StoresView.as_view()),
    url(r'^best/$', BestView.as_view()),
    url(r'^(?P<store_name>\w+)/search/$', SearchView.as_view()),
    url(r'^(?P<store_name>\w+)/$', SalesView.as_view()),
)

game_sale/sales/models.py
from django.db import models
import datetime
from parser.parse import STORES
from django.utils.timezone import utc

CHOICES_STORES = [(s, s) for s in STORES]


class Sale(models.Model):
    store = models.CharField(max_length=100, choices=CHOICES_STORES)
    name = models.CharField(max_length=255)
    name_real = models.CharField(max_length=255, blank=True)

    link = models.CharField(max_length=255, blank=True)
    image = models.CharField(max_length=255, blank=True)

    price_old = models.FloatField(default=0)
    price_now = models.FloatField(default=0)
    discount = models.PositiveIntegerField(default=0)

    is_bundle = models.BooleanField(default=False)
    is_dlc = models.BooleanField(default=False)

    is_active = models.BooleanField(default=False)
    expire = models.DateTimeField(default=lambda: datetime.datetime.now().replace(tzinfo=utc) + datetime.timedelta(days=1))
    updated = models.DateTimeField()
    price_updated = models.DateTimeField()  # Дата последнего обновления цены

    def __str__(self):
        return self.store + ' - ' + self.name


class Store(models.Model):
    store = models.CharField(max_length=100, choices=CHOICES_STORES)
    count = models.PositiveIntegerField(default=0)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.store + ' - ' + self.updated.isoformat()


class Chart(models.Model):
    sale = models.ForeignKey('Sale')
    price_old = models.FloatField(default=0)
    price_now = models.FloatField(default=0)
    discount = models.PositiveIntegerField(default=0)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.sale.store + ' - ' + self.sale.name


# http://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml

game_sale/sales/forms.py
# -*- coding: utf-8 -*-
from django import forms
from parser.parse import STORES

CHOICES_STORE = [(s, STORES[s]['name']) for s in STORES]
#CHOICES_STORE.insert(0, ('', 'магазин...'))


class MainSearchForm(forms.Form):
    # store = forms.ChoiceField(choices=CHOICES_STORE, required=False,
    #                           widget=forms.Select(attrs={'class': 'form-control'}))
    stores = forms.MultipleChoiceField(choices=CHOICES_STORE, required=False,
                                       widget=forms.SelectMultiple())
    price_from = forms.IntegerField(
        required=False,
        widget=forms.NumberInput(attrs={'class': 'form-control', 'style': 'max-width: 120px;', 'placeholder': 'цена от...'})
    )
    price_to = forms.IntegerField(
        required=False,
        widget=forms.NumberInput(attrs={'class': 'form-control', 'style': 'max-width: 120px;', 'placeholder': 'цена до...'})
    )
    name = forms.CharField(
        required=False,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'название...'})
    )

game_sale/sales/views.py
# -*- coding: utf-8 -*-
from collections import defaultdict, OrderedDict
from django.db.models import Q
from django.views.generic import ListView, DetailView
import time
from django.forms.models import model_to_dict
import datetime
from backend.views import BackendView
from parser.parse import STORES
from parser.tasks import sales_parse, search_parse, search_store_parse
from sales.forms import MainSearchForm
from sales.models import Sale, Store, Chart
from utils.filters_form_mixin import FiltersFormMixin
from django.utils.timezone import utc

STORES_LIST = STORES.keys()


class ParseView(BackendView):
    """
    Ручной запуск парсера скидок
    """
    def get(self, request, store_name=None):
        sales_parse(store_name)
        return self.response([])


class SleepView(BackendView):
    """

    """
    def get(self, request):
        time.sleep(60 * 5)
        return self.response([])


class StoresView(BackendView):
    """
    Список магазинов и их последних обновлений
    """
    def get(self, request):
        result = []
        for store_name, info in STORES.items():
            store = Store.objects.get_or_create(store=store_name)[0]
            info['id'] = store_name
            info['updated'] = time.mktime(store.updated.timetuple())
            info['count'] = store.count
            result.append(info)
        return self.response(result)


class SalesView(BackendView):
    """
    Получить все скидки из магазина. В url передать название магазина
    """
    @staticmethod
    def get_sales(store_name):
        sales = Sale.objects.filter(store=store_name).filter(is_active=True)
        results = []
        for sale in sales:
            sale.price_old_rub = sale.price_old
            sale.price_now_rub = sale.price_now

            results.append({
                'store': store_name,
                'id': sale.id,
                'name': sale.name,
                'store_id': sale.id,
                'link': sale.link,
                'image': sale.image,
                'price_old_rub': sale.price_old_rub,
                'price_now_rub': sale.price_now_rub,
                'discount': sale.discount,
                'updated': time.mktime(sale.updated.timetuple()),
                'price_updated': time.mktime(sale.price_updated.timetuple()),

                'is_bundle': sale.is_bundle,
                'is_dlc': sale.is_dlc,
            })
        return results

    def get(self, request, store_name):
        if store_name in STORES_LIST:
            return self.response(self.get_sales(store_name))
        return self.response_error(100, 'Unknown store')


class BestView(BackendView):
    """
    Получить список самых больших скидок

    Параметры:
        limit
        skip
        min_price_old_rub
    """
    def get(self, request):
        try:
            limit = int(request.GET.get('limit', 10))
        except ValueError:
            limit = 10
        try:
            min_price_old_rub = int(request.GET.get('min_price_old_rub', 0))
        except ValueError:
            min_price_old_rub = 0
        try:
            skip = int(request.GET.get('skip', 0))
        except ValueError:
            skip = 0

        sales = Sale.objects.order_by('-discount').filter(price_old_rub__gte=min_price_old_rub)[skip:skip+limit]
        sales = [model_to_dict(sale) for sale in sales]
        for sale in sales:
            del sale['store_type']
            del sale['genre']
            del sale['platforms']
            del sale['release']
        return self.response(sales)


class SearchView(BackendView):
    """
    Поиск игр в магазинах. В url передать название магазина

    Параметры:
        query   - текст запроса не менее 3-х символов
    """
    def get(self, request, store_name):
        if not store_name in STORES_LIST:
            return self.response_error(100, 'Unknown store')

        query = request.GET.get('query', '')
        games = []
        if len(query) > 3:
            games = search_store_parse(store_name, query)
        return self.response(games)


class MainView(FiltersFormMixin, ListView):
    template_name = 'sales/main.html'
    success_url = '/'
    context_object_name = 'sales'
    paginate_by = 50
    form_class = MainSearchForm

    def get_queryset(self):
        sale = Sale.objects
        filters = self.get_filters()
        if 'stores' in filters:
            sale = sale.filter(store__in=filters['stores'])
        if 'name' in filters:
            sale = sale.filter(name__icontains=filters['name'])
        if 'price_from' in filters:
            sale = sale.filter(price_now_rub__gte=filters['price_from'])
        if 'price_to' in filters:
            sale = sale.filter(price_now_rub__lte=filters['price_to'])
        sale = sale.filter(is_active=True).filter(is_bundle=False).filter(expire__gt=datetime.datetime.now().replace(tzinfo=utc))
        return sale.order_by('is_dlc', '-discount')

    def get_context_data(self, **kwargs):
        context = super(MainView, self).get_context_data(**kwargs)
        if self.request.is_mobile:
            page_extension = 3
        else:
            page_extension = 5

        pages = context['paginator'].num_pages
        page = context['page_obj'].number
        start_page = page - page_extension
        end_page = page + page_extension
        if start_page < 1:
            end_page += -start_page + 1
            start_page = 1

        if end_page > pages:
            start_page -= end_page - pages - 1
            if start_page < 1:
                start_page = 1
            end_page = pages + 1

        context['page_range'] = [i for i in range(start_page, end_page)]
        for sale in context['sales']:
            sale.store_name_view = STORES.get(sale.store, {'name': ''})['name']
            sale.store_site_view = STORES.get(sale.store, {'site': ''})['site']
            sale.currency = {'rub': 'руб.', 'usd': 'USD'}[STORES.get(sale.store, {'currency': 'usd'})['currency']]
            sale.image = sale.image[:-4] + '_h48.jpg'
        return context


class SaleView(DetailView):
    template_name = 'sales/sale.html'
    model = Sale

    def get_context_data(self, **kwargs):
        context = super(SaleView, self).get_context_data(**kwargs)
        sale = context['sale']
        if not sale.name_real:
            sale.name_real = sale.name
        charts = Chart.objects.filter(Q(sale__name=sale.name_real) |
                                      Q(sale__name_real=sale.name_real)
                                      ).order_by('created')
        dates = []

        first_date = charts[0].created
        now = datetime.datetime.now().replace(tzinfo=utc) + datetime.timedelta(days=1)
        i = -3
        while True:
            date = first_date + datetime.timedelta(days=i)
            if date > now:
                break
            date = date.strftime('%d-%m-%Y')
            dates.append(date)
            i += 1

        datas = defaultdict(dict)
        sales = set()
        for chart in charts:
            sales.add(chart.sale.id)
            date = chart.created.strftime('%d-%m-%Y')
            # Из одного магазина может прийти две одинаковые игры, нужно взять меньшую цену
            if date in datas[chart.sale.store]:
                if chart.price_now < datas[chart.sale.store][date]['price_now']:
                    datas[chart.sale.store][date] = {'price_old': chart.price_old,
                                                     'price_now': chart.price_now,
                                                     'price': chart.price_now}
            else:
                datas[chart.sale.store][date] = {'price_old': chart.price_old,
                                                 'price_now': chart.price_now,
                                                 'price': chart.price_now}

        for store, data in datas.items():
            old_price = None
            for date in reversed(dates):
                if not date in data and old_price is None:
                    continue
                elif not date in data:
                    data[date] = {'price': old_price}
                else:
                    old_price = data[date]['price_old']

        series = []
        for store, data in datas.items():
            sery = {
                'name': STORES[store]['name'],
                'color': STORES[store]['color'],
                'data': []
            }
            for date in dates:
                if date in data:
                    sery['data'].append('[Date.UTC(%d, %d, %d), %d]' %
                                        (
                                            int(date.split('-')[2]),
                                            int(date.split('-')[1]) - 1,
                                            int(date.split('-')[0]),
                                            data[date]['price']
                                        )
                                        )
            sery['data'] = ','.join(sery['data'])
            series.append(sery)

        sales = Sale.objects.filter(id__in=sales)
        for sale in sales:
            sale.store_name_view = STORES.get(sale.store, {'name': ''})['name']
            sale.store_site_view = STORES.get(sale.store, {'site': ''})['site']
        context['sales'] = sales
        context['series'] = series
        return context

game_sale/sales/templates/sales/base.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ru">
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block meta %}{% endblock %}
    <title>Game Sales - поиск по игровым скидкам</title>
    <link rel="shortcut icon" type="image/ico" href="{{ STATIC_URL }}favicon_smooth.ico" />
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}bootstrap/css/bootstrap.min.css">
    {% block link %}{% endblock %}
    {% block link_desktop %}{% endblock %}
    <style>
    {% if not is_mobile %}
        body { padding-top: 70px; }
        .jumbotron { padding-top: 10px; padding-bottom: 10px; margin-bottom: 10px; }
    {% endif %}
    </style>
</head>
<body>

    <div class="navbar navbar-inverse {% if not is_mobile %}navbar-fixed-top{% endif %}" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/"><span class="glyphicon glyphicon-tower" style="margin-right: 5px;"></span>Game Sales{% if not is_mobile %} - поиск по игровым скидкам{% endif %}</a>
            </div>
            <div class="navbar-collapse collapse">
              <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li><a href="/admin/">Account: {{ user.username }}</a></li>
                {% endif %}
              </ul>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row">
        {% block content %}
        {% endblock %}
        </div>
    </div>

    <div style="text-align: center; padding-bottom: 10px;">Game Sales 2014. Contacts: <a href="mailto:turlicht@yandex.ru">turlicht@yandex.ru</a></div>

    <script type="text/javascript" src="{{ STATIC_URL }}jquery/jquery-1.11.1.min.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}bootstrap/js/bootstrap.min.js"></script>

    {% block script %}{% endblock %}
    {% block script_desktop %}{% endblock %}

    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-54391124-1', 'auto');
      ga('send', 'pageview');
    </script>

</body>
</html>

game_sale/sales/templates/sales/main.html
{% extends "sales/base.html" %}

{% block meta %}
    <meta name="description" content="Поиск по скидкам и распродажам компьютерных игр, продаваемых через сервисы цифрового распространения: Steam, Origin, Uplay и т.п."/>
{% endblock %}

{% block link_desktop %}
    <link rel="stylesheet" href="{{ STATIC_URL }}bootstrap/css/bootstrap-multiselect.css" type="text/css"/>
{% endblock %}

{% block content %}

    {% if not is_mobile %}
    <form action="{% url 'main' %}" method="post" role="form" class="form-inline">
        {% csrf_token %}
                {{ form.stores }}
                {{ form.name }}
        {% if False %}
                {{ form.price_from }}
                {{ form.price_to }}
        {% endif %}
        <button type="submit" class="btn btn-default">Поиск</button>
    </form>
    {% endif %}

    <div class="table-responsive">
        <table class="table table-striped">
        <thead>
            {% if is_mobile %}
            {% else %}
            <tr class="table-head">
                <th></th>
                <th>Название</th>
                <th>Магазин</th>
                <th>Цена</th>
                <th>Скидка</th>
                {% if user.is_authenticated %}<th><span class="glyphicon glyphicon-th"></span></th>{% endif %}
            </tr>
            {% endif %}
        </thead>
        <tbody>
        {% for sale in sales %}
            <tr class="table-content">
            {% if is_mobile %}
                <td style="padding: 4px;"><img src="{{ sale.image }}" height="48" ></td>
                <td>
                    <a target="_blank" rel="nofollow" class="link-content" href="{{ sale.link }}">{{ sale.name }}</a>
                    <br>{{ sale.price_now|floatformat }} {{ sale.currency }}<del>{{ sale.price_old|floatformat }} {{ sale.currency }}</del>
                </td>
                <td><a target="_blank" rel="nofollow" class="link-content" href="{{ sale.store_site_view }}">{{ sale.store_name_view }}</a></td>
            {% else %}
                <td style="padding: 4px;"><img src="{{ sale.image }}" height="48" ></td>
                <td><a target="_blank" rel="nofollow" class="link-content" href="{{ sale.link }}">{{ sale.name }}</a>
                {% if user.is_authenticated %}<br>{{ sale.name_real }}{% endif %}
                </td>
                <td><a target="_blank" rel="nofollow" class="link-content" href="{{ sale.store_site_view }}">{{ sale.store_name_view }}</a></td>
                <td>{{ sale.price_now|floatformat }} {{ sale.currency }}<br><del>{{ sale.price_old|floatformat }} {{ sale.currency }}</del></td>
                <td>{{ sale.discount }}%<br>
                    <a href="{% url 'sale-detail' sale.id %}">
                        <span class="glyphicon glyphicon-stats" style="margin-left: 5px;"></span>
                    </a>
                    {% if sale.is_bundle %}
                        <span id="bandle" class="glyphicon glyphicon-gift" style="margin-right: 5px;"></span>
                    {% endif %}
                </td>
                {% if user.is_authenticated %}
                    <td><a target="_blank" href="/admin/sales/sale/{{ sale.id }}/"><span class="glyphicon glyphicon-pencil"></span></a></td>
                {% endif %}
            {% endif %}
            </tr>
        {% endfor %}
        </tbody>
        </table>
    </div>
    {% if not sales %}
        Ничего не найдено, попробуйте изменить запрос. В базе хранятся только игры со скидками.
    {% endif %}

    {% if is_paginated %}
    <ul class="pagination">
        <li><a rel="nofollow" href="?page=1">&laquo;</a></li>
        {% for page in page_range %}
            {% if page_obj.number == page %}
                <li class="active"><a rel="nofollow" href="?page={{ page }}">{{ page }}</a></li>
            {% else %}
                <li><a rel="nofollow" href="?page={{ page }}">{{ page }}</a></li>
            {% endif %}
        {% endfor %}
        <li><a rel="nofollow" href="?page={{ paginator.num_pages }}">&raquo;</a></li>
    </ul>
    {% endif %}

{% endblock %}

{% block script_desktop %}
    <script type="text/javascript" src="{{ STATIC_URL }}bootstrap/js/bootstrap-multiselect.js"></script>

    <script type="text/javascript">
    $(document).ready(function() {
        $('#id_stores').multiselect({
            numberDisplayed: 5,
            nonSelectedText: "магазины...",
            includeSelectAllOption: true,
            selectAllText: 'Все магазины',
            nSelectedText: 'Выбрано: ',

            buttonText: function(options, select) {
                if (options.length == 0) {
                    return this.nonSelectedText + ' <b class="caret"></b>';
                }
                else {
                    if (options.length > this.numberDisplayed) {
                        return this.nSelectedText + ' ' + options.length + ' <b class="caret"></b>';
                    }
                    else {
                        var selected = '';
                        options.each(function() {
                            var label = ($(this).attr('label') !== undefined) ? $(this).attr('label') : $(this).html();
                            selected += label + ', ';
                        });
                        return selected.substr(0, selected.length - 2) + ' <b class="caret"></b>';
                    }
                }
            }
        });
    });
    </script>

    <script type="text/javascript">
        $('#bandle').popover({
            'trigger': 'hover',
            'title': 'Bundle',
            'placement': 'right',
            'content': 'Комплект, состоящий из нескольких игр'
        })
    </script>

{% endblock %}

game_sale/sales/templates/sales/sale.html
{% extends "sales/base.html" %}

{% block meta %}
    <meta name="description" content="Статистика цен игры"/>
{% endblock %}

{% block link %}
    <link rel="stylesheet" href="{{ STATIC_URL }}blueimp/blueimp-gallery.min.css">
    <link rel="stylesheet" href="{{ STATIC_URL }}bootstrap/css/bootstrap-image-gallery.min.css">
{% endblock %}

{% block content %}
    <h1>{{ object.name }}</h1>
    <div id="container" style="width:100%; height:400px;"></div>

    <div class="row">
        <div class="col-md-6">
            <div class="table-responsive">
                <table class="table table-striped">
                <thead>
                    <tr class="table-head">
                        <th>Название</th>
                        <th>Магазин</th>
                        {% if user.is_authenticated %}<th><span class="glyphicon glyphicon-th"></span></th>{% endif %}
                    </tr>
                </thead>
                <tbody>
                {% for sale in sales %}
                    <tr class="table-content">
                        <td><a target="_blank" rel="nofollow" class="link-content" href="{{ sale.link }}">{{ sale.name }}</a>
                        {% if user.is_authenticated %} ({{ sale.name_real }}){% endif %}
                        </td>
                        <td><a target="_blank" rel="nofollow" class="link-content" href="{{ sale.store_site_view }}">{{ sale.store_name_view }}</a></td>
                        {% if user.is_authenticated %}
                            <td><a target="_blank" href="/admin/sales/sale/{{ sale.id }}/"><span class="glyphicon glyphicon-pencil"></span></a></td>
                        {% endif %}
                    </tr>
                {% endfor %}
                </tbody>
                </table>
            </div>
        </div>
        <div class="col-md-6"></div>
    </div>


{% endblock %}

{% block script %}
    <script type="text/javascript" src="{{ STATIC_URL }}blueimp/jquery.blueimp-gallery.min.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}bootstrap/js/bootstrap-image-gallery.min.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}highcharts/js/highcharts.js"></script>

    <script type="text/javascript">
        $(function () {
            $('#container').highcharts({
                chart: {
                    zoomType: 'x'
                },
                title: {
                    text: 'История изменения цены',
                    x: -20 //center
                },
                subtitle: {
                    text: 'График отражает движение скидочных цен',
                    x: -20 //center
                },
                xAxis: {
                    type: 'datetime',
                    minTickInterval: 24 * 3600 * 1000,
                    dateTimeLabelFormats: {
                        millisecond: '%H:%M:%S.%L',
                        second: '%H:%M:%S',
                        minute: '%H:%M',
                        hour: '%H:%M',
                        day: '%e. %b.',
                        week: '%e. %b',
                        month: '%b \'%y',
                        year: '%Y'
                    }
                },
                yAxis: {
                    title: {
                        text: 'Цена, руб.'
                    },
                    plotLines: [{
                        value: 0,
                        width: 1,
                        color: '#808080'
                    }]
                },
                tooltip: {
                    valueSuffix: ' руб.'
                },
                legend: {
                    layout: 'horizontal',
                    align: 'center',
                    verticalAlign: 'bottom',
                    borderWidth: 0
                },
                series: [
                    {% for sery in series %}
                        {
                            name: '{{ sery.name }}',
                            color: '{{ sery.color }}',
                            pointInterval: 24 * 3600 * 1000,
                            data: [{{ sery.data }}]
                        },
                    {% endfor %}
                ]
            });
        });
    </script>

{% endblock %}